name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [4, 5, 6, 8, 10, 12, 14]
        mongodb-version:
          ["2.6", "3.0", "3.2", "3.4", "3.6", "4.0", "4.2", "4.4", "5.0"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: start mongodb
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: |
          npm i
          npm test
